#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/chat_app
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#
#server:
#  port: 8443
#  error:
#    include-message: always
#
##  ssl:
##    key-store-type: PKCS12
##    #       key-store: file:/Users/bambook/src/main/resources/ssl/keystore.p12
##    key-store: classpath:ssl/keystore.p12
##    key-store-password: 1234
##    key-alias: tomcat
##    enabled: true
#
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://postgres:GLxFhXA9!WZRG3Z@db.dgchmoyspysfcbuajwhj.supabase.co:5432/postgres
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
#  port: ${PORT:8443}
  port: 9090
  error:
    include-message: always