spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Форматирует SQL для читаемости
        use_sql_comments: true  # Добавляет комментарии к запросам
    hibernate:
      ddl-auto: update  # Убедитесь, что таблицы создаются автоматически

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.cudwuwgftqghyrwkbveg}
    password: ${SPRING_DATASOURCE_PASSWORD:atai123atai}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG  # Выводит сами SQL-запросы
    org.hibernate.type.descriptor.sql: TRACE  # Выводит параметры запросов (bind values)

server:
  port: ${PORT:3232}
  error:
    include-message: always