spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.cudwuwgftqghyrwkbveg}
    password: ${SPRING_DATASOURCE_PASSWORD:atai123atai}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:9393}
  error:
    include-message: always